### ISSUE TITLE
How to successfully compile?

### ISSUE THREAD

**Issue by DarkMatterMatt** [JMMcKinneyWPI/GyroPIDLibrary#1]
Sorry if I'm missing something really easy, but I'd like to use your library for doing gyroscope based turns. I downloaded your library, and attempted to compile it in both RobotC 3, and RobotC 4. Both failed, with a few errors.

```
22.027: **Error**:'error' is not a 'struct' element of struct reference 'pid'
22.043: **Error**:Unexpected '`' during parsing
22.067: **Error**:Undefined variable 'error'. 'short' assumed.
49: **Error**:Undefined procedure 'pidReset'.
90: **Error**:Undefined variable 'calibrationInProgress'. 'short' assumed.
```

Line 22 is the PIDController.h, 22.027 is line 027 of PIDController.h

I got rid of the tilde on line 22.043, which I assume was a typo.
I also added `error` to the struct "pid", as a float.
Line 90 was `SensorValue[calibrationInProgress] = 1;`, probably referring to a LED that would indicate when calibration was in progress. I deleted lines referring to that sensor.
I guess `pidReset` is just resetting it back to it's original values, maybe the same as doing `pidInit(gyroPid, 2, 0, 0.15, 2);`. I replaced the `pidReset` call with `pidInit(gyroPid, 2, 0, 0.15, 2);`.
Now I'm left with an error I don't know what to do about; `22.067: **Error**:Undefined variable 'error'. 'short' assumed.` 
"error" is referred to three times at the bottom of the PIDController. What is it and where should I define it please?

```
if(abs(error) > pid.epsilon)
    pid.errorSum += error * pid.dT;
    pid.output = error * pid.kP + pid.errorSum * pid.kI + rate * pid.kD;
```

Thanks for the amazing library, would be awesome if I could get it working for our robot this year :smile:

**Comment by JMMcKinneyWPI** [comment]
Hi!

This codebase was actually a little old, I have since made a more robust and complete version that I am maintaining here: https://bitbucket.org/VRCNERD/nerd_robotc.

I have updated this repo with the current version of the code from over there, but I would check the new one for any updates or changes to my libs.

There are now some example files you can take a look at that may be more useful than what I had before as well. Let me know if you have any other questions.
